version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: Microsoft.ApplicationInsights
    versions:
    - 2.17.0
  - dependency-name: Xamarin.Essentials
    versions:
    - 1.6.1
  - dependency-name: Microsoft.AppCenter.Analytics
    versions:
    - 4.1.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
