# Project Information
site_name: Prism.Plugin.Logging
site_description: Documentation for the Prism Logging Plugin
site_author: Dan Siegel
site_url: http://logging.prismplugins.com

# Repository
repo_name: dansiegel/Prism.Plugin.Logging
repo_url: https://github.com/dansiegel/Prism.Plugin.Logging
edit_uri: ''

# Copyright
copyright: 'Copyright &copy; 2016 - 2021 Dan Siegel'

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  icon:
    repo: fontawesome/brands/github
  logo: assets/prism-logo.png
  favicon: assets/favicon.ico
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: 'white'
    accent: 'cyan'

# Social
extra:
  social:
    - icon: fontawesome/brands/html5
      link: https://dansiegel.net
    - icon: fontawesome/brands/github
      link: https://github.com/dansiegel
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/dansiegel
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DanJSiegel
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/DanSiegel

# Extensions
markdown_extensions:
  - admonition:
  - codehilite:
      linenums: false
  - toc:
      permalink: true

nav:
  - Prism:
    - Prism: http://prismlibrary.github.io/docs
  - Logging:
    - Getting Started: index.md
    - Abstractions: abstractions.md
    - Aggregate Logger: aggregate-logger.md
    - App Center: appcenter/index.md
    - Application Insights: appinsights/index.md
    - Graylog: graylog/index.md
    - Loggly: loggly/index.md
    - Socket Logger: socket/index.md
    - Syslog: syslog/index.md
    - Samples: samples.md
  - Popups:
    - Popups: http://popups.prismplugins.com
  - Container Extensions:
    - Container Extensions: http://prismplugins.com
  - Mobile.BuildTools:
    - Mobile.BuildTools: http://mobilebuildtools.com

google_analytics:
  - UA-153405647-2
  - auto
